import type { Topic, TopicId } from "@/types/learning";

const make = (id: string, title: string, intuition: string, why: string, workedExample: string[], quant: string, commonMistake: string, critical = false) => ({ id, title, intuition, why, workedExample, quant, commonMistake, critical });

export const phaseOneTopics: Topic[] = [
  { id:"order", number:1, title:"Order of Operations", short:"Make expressions mean one thing.", color:"#8373f5", description:"A shared order makes every arithmetic expression unambiguous.", prerequisites:[], concepts:[
    make("order.precedence","Why order exists","An expression is a recipe. Changing the step order can change the final dish.","Without an agreed order, 8 + 6 × 4 could mean two different things.",["8 + 6 × 4","6 × 4 = 24","8 + 24 = 32"],"Position-size formulas mix prices, risk and fees.","Doing addition before multiplication changes the expression.",true),
    make("order.left-to-right","Equal priority","Division and multiplication are teammates; neither always wins.","When operations share a level, solve the one that appears first.",["18 ÷ 3 × 2","= 6 × 2","= 12"],"Execution formulas often use several divisions and multiplications.","Multiplication does not always come before division.",true),
    make("order.parentheses","Parentheses","Parentheses are a clear instruction: finish this small job first.","They let you intentionally override the normal recipe.",["(12 − 3) × 2","= 9 × 2","= 18"],"Useful when grouping a trade formula.","Ignoring brackets."),
    make("order.powers","Powers in expressions","A power is repeated multiplication, so complete it before the surrounding operations.","It is one compact operation inside the expression.",["2 + 3² × 4","= 2 + 9 × 4","= 38"],"Compounding formulas use powers.","Reading 3² as 3 × 2.")
  ]},
  { id:"fractions", number:2, title:"Fractions", short:"See equal parts of a whole.", color:"#e85d75", description:"Fractions describe equal-sized parts and let you compare quantities precisely.", prerequisites:["order.precedence"], concepts:[
    make("fractions.meaning","Meaning of a fraction","The denominator says how many equal parts make one whole. The numerator says how many parts you have.","Equal pieces are essential: 3/4 is meaningful because every fourth is the same size.",["3/4","four equal pieces","three selected"],"Partial exits and probabilities are fractions of a total.","Counting unequal pieces as a fraction.",true),
    make("fractions.equivalent","Equivalent fractions","Cutting the same amount into more pieces does not change the amount.","Both numerator and denominator scale by the same factor.",["1/2","= 2/4","= 4/8"],"A 50% position is 1/2 of capital.","Thinking 2/4 is larger than 1/2."),
    make("fractions.simplifying","Simplifying","Simplifying gives the same amount in fewer, larger groups.","Remove a common factor from the top and bottom.",["6/8","divide both by 2","= 3/4"],"Simpler ratios make risk numbers easier to read.","Subtracting the same number from top and bottom."),
    make("fractions.comparing","Comparing fractions","Bars with the same total width reveal which fraction occupies more space.","You can rewrite pieces to the same size before comparing.",["2/3 ≈ 0.667","3/5 = 0.6","therefore 2/3 is larger"],"Compare probability or allocation choices.","Comparing only the numerators."),
    make("fractions.common-denominator","Common denominators","You can add pieces only when their size matches.","Rewrite one-half as two fourths so every piece is a fourth.",["1/2 + 1/4","2/4 + 1/4","= 3/4"],"Combining partial allocations needs a common unit.","1/2 + 1/4 = 2/6.",true),
    make("fractions.multiply","Fraction multiplication","Taking one part of another part makes a smaller overlap.","Area models show 1/2 of 1/3 is 1/6.",["1/2 × 1/3","overlap of half and third","= 1/6"],"Probabilities can multiply for independent events.","Adding denominators when multiplying."),
    make("fractions.divide","Fraction division","Division asks how many groups fit. How many quarters fit in a half? Two.","The reciprocal rule is a shortcut for this grouping question.",["1/2 ÷ 1/4","how many quarters in a half?","= 2"],"Useful when converting units and sizing partial orders.","Dividing both top and bottom without asking what fits.",true),
    make("fractions.improper","Mixed numbers","An improper fraction contains more than one whole.","Group full denominators, then keep the remainder.",["8/3","= 2 wholes + 2/3","= 2 2/3"],"A leverage or allocation number can exceed one whole.","Hiding the extra whole."),
    make("fractions.conversions","Fraction conversions","A fraction, decimal and percent can name the exact same amount.","Divide top by bottom, then multiply by 100 for percent.",["3/4","= 0.75","= 75%"],"Returns and probabilities switch between all three forms.","Treating 0.75% as 75%.")
  ]},
  { id:"decimals", number:3, title:"Decimals", short:"Use place value for precision.", color:"#269b93", description:"Decimals extend whole numbers with tenths, hundredths and smaller parts.", prerequisites:["fractions.meaning"], concepts:[
    make("decimals.place-value","Place value","A digit changes value when its place changes.","Every step left is ten times bigger; every step right is ten times smaller.",["23.475","2 tens + 3 ones","4 tenths + 7 hundredths + 5 thousandths"],"Prices and spreads use decimal places.","Thinking 0.04 means four tenths.",true),
    make("decimals.comparison","Comparing decimals","Write both values with the same number of places, then compare.","0.8 is 0.80, so it is greater than 0.75.",["0.80","0.75","80 hundredths > 75 hundredths"],"Tiny price differences matter.","Thinking more digits always means larger."),
    make("decimals.operations","Decimal operations","Line up decimal places because each column is a different unit.","Tenths must sit under tenths and hundredths under hundredths.",["2.40 + 0.65","= 3.05"],"Fees and fills must use exact place value.","Ignoring the decimal point."),
    make("decimals.scale","Powers of ten","Multiplying by 10 shifts digits left; dividing shifts them right.","The digits do not move physically—their place value changes.",["0.47 × 10 = 4.7","4.7 ÷ 100 = 0.047"],"Tick sizes and unit conversions use powers of ten.","Adding zeroes without tracking direction."),
    make("decimals.rounding","Rounding","Rounding is an honest approximation with a stated precision.","Look at the next digit to decide whether to stay or increase.",["3.476 to 2 places","next digit is 6","= 3.48"],"Reports often round returns, but calculations should keep precision.","Rounding too early.")
  ]},
  { id:"percentages", number:4, title:"Percentages", short:"Compare every amount to 100.", color:"#f29b38", description:"Percent literally means out of one hundred.", prerequisites:["fractions.conversions","decimals.place-value"], concepts:[
    make("percentages.meaning","Percent meaning","37% means 37 of 100 equal pieces.","It is another name for 37/100 or 0.37.",["37%","= 37/100","= 0.37"],"Market returns are usually reported as percentages.","Confusing 0.37 with 0.37%.",true),
    make("percentages.of-quantity","Percent of a quantity","First find one percent or turn the percent into a decimal part.","10% of 250 is ten groups of 1%, or 25.",["250 × 0.10","= 25"],"Fees, position allocations and win rates.","Dividing by the percent instead of multiplying."),
    make("percentages.change","Percentage change","A change becomes a percentage only compared with its starting value.","The old value is the reference, so a +30 move from 200 is 15%.",["200 → 230","+30","30/200 = 15%"],"Return is price change relative to entry.","Dividing by the new value.",true),
    make("percentages.successive","Successive changes","A loss after a gain acts on a new amount, not the original amount.","10% down from 110 is 11, not 10.",["100 → 110","+10%","110 → 99, −10%"],"Drawdowns and compounding are asymmetric.","Assuming +10% and −10% cancel.",true),
    make("percentages.compounding","Compounding","Each period grows from the previous period's value.","Repeated percentage growth is multiplication, not repeated addition.",["100 × 1.1³","= 133.1"],"Compound returns drive equity curves.","Adding 10 + 10 + 10 to capital.")
  ]},
  { id:"ratios", number:5, title:"Ratios & Proportions", short:"Compare two quantities clearly.", color:"#4b7bec", description:"Ratios preserve a relationship while amounts scale.", prerequisites:["fractions.meaning"], concepts:[
    make("ratios.meaning","Ratio meaning","3:2 says every three of one kind sit beside two of another kind.","A ratio compares two quantities directly.",["3 red : 2 blue","total = 5"],"Risk/reward compares reward with risk.","Calling 3:2 a percentage.",true),
    make("ratios.equivalent","Equivalent ratios","Scale both sides equally and the relationship stays unchanged.","3:2 becomes 6:4 by multiplying both by two.",["3:2","×2","6:4"],"Compare trade samples at different sizes.","Scaling one side only."),
    make("ratios.part-whole","Part to part vs whole","Red:blue is 3:2, but red:total is 3:5.","The denominator or second term changes when the question changes.",["3 red, 2 blue","red:blue = 3:2","red:total = 3:5"],"Win/loss ratio is not win rate.","Using wins:losses as wins:total.",true),
    make("ratios.proportion","Proportions","Equivalent fractions scale by the same multiplier.","If 3 becomes 12 by ×4, 5 becomes 20 by ×4.",["3/5 = 12/x","x = 20"],"Unit rates and position scaling.","Cross multiplying without seeing the scale.")
  ]},
  { id:"negatives", number:6, title:"Negative Numbers", short:"Use direction, not fear.", color:"#c66bda", description:"Negative values are positions below zero and moves in the opposite direction.", prerequisites:[], concepts:[
    make("negatives.number-line","Number line","Right means larger; left means smaller, even for negative values.","Distance and direction make signs visible.",["−3 + 5","move five right","= 2"],"Profit and loss moves an equity curve.","Thinking −8 is greater than −3.",true),
    make("negatives.subtract","Subtraction","Subtracting moves left. Subtracting a negative removes a left move, so it moves right.","Two signs describe different jobs: subtraction and negative direction.",["3 − (−2)","= 3 + 2","= 5"],"Offsets and P/L corrections use signs.","3 − (−2) = 1.",true),
    make("negatives.multiply","Signs in multiplication","Patterns stay regular as a factor passes zero.","Each step down in 3×2, 2×2, 1×2… reduces result by two.",["1×2 = 2","0×2 = 0","−1×2 = −2"],"Returns can be negative multipliers.","Memorizing signs without the pattern."),
    make("negatives.absolute","Absolute value","Absolute value is distance from zero, never direction.","Both −7 and 7 are seven units away.",["|−7| = 7"],"Drawdown size is often discussed as a positive magnitude.","Keeping the negative sign.")
  ]},
  { id:"exponents", number:7, title:"Powers & Exponents", short:"Repeated multiplication, compactly written.", color:"#e67b4e", description:"Powers compress repeated multiplication and reveal exponential growth.", prerequisites:["order.powers"], concepts:[
    make("exponents.meaning","Repeated multiplication","2³ means three copies of two multiplied together.","The exponent counts copies, not a value to multiply by.",["2³","= 2 × 2 × 2","= 8"],"Compounding is repeated multiplication.","2³ = 2 × 3.",true),
    make("exponents.rules","Exponent rules","When same bases multiply, all copies join together.","x² × x³ has five copies of x.",["x² × x³","= x⁵"],"Scale formulas efficiently.","Adding bases instead of exponents."),
    make("exponents.zero-negative","Zero and negative exponents","Move down one exponent by dividing by the base.","This pattern makes 2⁰ = 1 and 2⁻² = 1/4.",["2³=8 → 2²=4 → 2¹=2","2⁰=1 → 2⁻¹=1/2"],"Inverse quantities and scale.","Thinking any number to zero is zero.",true),
    make("exponents.growth","Linear vs exponential","Linear adds the same amount; exponential multiplies by the same amount.","The gap widens because each step uses a larger starting value.",["linear: 2,4,6,8","exponential: 2,4,8,16"],"Compound returns are exponential.","Expecting compound growth to be a straight line.")
  ]},
  { id:"roots", number:8, title:"Roots", short:"Find the side from the square.", color:"#5caf81", description:"Roots reverse powers and reveal a side length from a square's area.", prerequisites:["exponents.meaning"], concepts:[
    make("roots.meaning","Square roots","√81 asks for the side length of a square with area 81.","A 9 by 9 square has area 81.",["9² = 81","therefore √81 = 9"],"Standard deviation later uses a square root.","√81 = 81/2.",true),
    make("roots.perfect","Perfect squares","Perfect squares come from whole side lengths.","Knowing nearby squares creates intuition.",["7²=49","8²=64"],"Scale and distance calculations.","Thinking every root is a whole number."),
    make("roots.approximation","Approximating roots","√50 sits just above 7 because 50 sits just above 49.","Nearby square numbers bound the answer.",["7²=49 < 50","8²=64 > 50","√50 ≈ 7.07"],"Later variance becomes standard deviation.","Rounding √50 to 8.",true),
    make("roots.cube","Cube roots","A cube root reverses cubing, just as a square root reverses squaring.","∛27 asks what number cubed is 27.",["3³ = 27","∛27 = 3"],"Prepares inverse-function thinking.","Using square-root rules for cubes.")
  ]}
];

export const topicById = Object.fromEntries(phaseOneTopics.map(t => [t.id, t])) as Record<TopicId, Topic>;
export const conceptById = Object.fromEntries(phaseOneTopics.flatMap(t => t.concepts.map(c => [c.id, c])));
