"use client";

import { useEffect, useState } from "react";
import { BarChart3, BookOpen, Calculator, ChevronLeft, ChevronRight, FlaskConical, Home, Menu, Moon, Sparkles, Sun, Target, Trophy, X } from "lucide-react";
import { Progress } from "@/components/ui/progress";
import { DecimalLab, ExponentLab, FractionLab, MarketReturnLab, NumberLineLab, OrderMachine, PercentageLab, RatioLab, RootLab } from "@/components/math-labs";
import { QuantLab } from "@/components/quant/quant-lab";
import { phaseOneTopics, topicById } from "@/content/phase-1/topics";
import { answersMatch } from "@/lib/answer-parser";
import { recordEvidence, topicMastery } from "@/lib/mastery";
import { generateFinalTest, generateQuestion, generateSession } from "@/lib/question-engine";
import { dueReview, loadState, saveState } from "@/lib/storage";
import type { Difficulty, LearningState, Question, TopicId } from "@/types/learning";

type Screen = "home" | "learn" | "practice" | "visual" | "quant" | "tests" | "progress";
type Source = "guided" | "practice" | "test" | "diagnostic";
const nav = [{ id:"home", label:"Home", Icon:Home }, { id:"learn", label:"Learn", Icon:BookOpen }, { id:"practice", label:"Practice", Icon:Target }, { id:"visual", label:"Visual Lab", Icon:FlaskConical }, { id:"quant", label:"Quant Lab", Icon:Calculator }, { id:"tests", label:"Tests", Icon:Trophy }, { id:"progress", label:"Progress", Icon:BarChart3 }] as const;
const label = (score:number) => score < 40 ? "Learning" : score < 70 ? "Developing" : score < 85 ? "Strong" : "Mastered";

export function LearningApp() {
  const [screen, setScreen] = useState<Screen>("home");
  const [state, setState] = useState<LearningState>(() => loadState());
  const [topicId, setTopicId] = useState<TopicId>(() => loadState().lastTopic);
  const [more, setMore] = useState(false);
  useEffect(() => { saveState(state); }, [state]);
  const mastery = (id:TopicId) => topicMastery(topicById[id], state);
  const overall = Math.round(phaseOneTopics.reduce((sum, topic) => sum + mastery(topic.id), 0) / phaseOneTopics.length);
  const choose = (id:TopicId) => { setTopicId(id); setState((old) => ({ ...old, lastTopic:id })); setScreen("learn"); setMore(false); };
  const record = (question:Question, correct:boolean, source:Source) => setState((old) => recordEvidence(old, question.topicId, question.conceptId, { correct, difficulty:question.difficulty, source, questionId:question.id, at:Date.now() }));
  const dark = state.theme === "dark";
  return <div className={dark ? "dark" : ""}><main className="min-h-screen bg-[#f6f7fb] text-slate-900 dark:bg-slate-950 dark:text-slate-50">
    <aside className="fixed inset-y-0 left-0 z-30 hidden w-72 border-r border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900 lg:flex lg:flex-col"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-violet-600 text-xl font-black text-white">∑</div><div><h1 className="font-black">QuantMath</h1><p className="text-xs text-slate-500">Learn by seeing</p></div></div><nav className="mt-8 space-y-1">{nav.map(({id, label:navLabel, Icon}) => <button key={id} onClick={() => setScreen(id)} className={`flex w-full items-center gap-3 rounded-xl px-3.5 py-3 text-left text-sm font-bold ${screen === id ? "bg-violet-600 text-white" : "text-slate-500 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800"}`}><Icon size={18}/>{navLabel}</button>)}</nav><div className="mt-auto rounded-2xl bg-slate-950 p-4 text-white"><p className="text-xs font-bold uppercase tracking-wider text-violet-200">Phase 1</p><p className="mt-1 font-bold">Mathematical foundations</p><Progress value={overall} className="mt-4 h-2 bg-white/15 [&_[data-slot=progress-indicator]]:bg-emerald-400"/><p className="mt-2 text-xs text-slate-300">{overall}% concept mastery</p></div></aside>
    <header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-slate-200/80 bg-[#f6f7fb]/90 px-4 backdrop-blur dark:border-slate-800 dark:bg-slate-950/90 sm:px-8 lg:ml-72"><p className="text-sm font-bold text-slate-500">Phase 1 · {screen === "learn" ? topicById[topicId].title : nav.find((item) => item.id === screen)?.label}</p><button aria-label="Toggle color mode" onClick={() => setState((old) => ({ ...old, theme:old.theme === "dark" ? "light" : "dark" }))} className="rounded-xl border border-slate-200 bg-white p-2.5 text-slate-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300">{dark ? <Sun size={18}/> : <Moon size={18}/>}</button></header>
    <div className="mx-auto max-w-6xl px-4 py-6 pb-24 sm:px-8 sm:py-9 lg:ml-72">{screen === "home" && <HomePage state={state} overall={overall} mastery={mastery} choose={choose} review={() => setScreen("practice")}/>} {screen === "learn" && <LessonPage topicId={topicId} mastery={mastery(topicId)} choose={choose} record={record}/>} {screen === "practice" && <PracticePage defaultTopic={topicId} record={record}/>} {screen === "visual" && <VisualPage/>} {screen === "quant" && <QuantLab/>} {screen === "tests" && <TestsPage record={record} setState={setState}/>} {screen === "progress" && <ProgressPage state={state} mastery={mastery}/>}</div>
    <nav className="fixed inset-x-0 bottom-0 z-40 grid grid-cols-5 border-t border-slate-200 bg-white/95 px-1 py-2 backdrop-blur dark:border-slate-800 dark:bg-slate-900/95 lg:hidden">{nav.slice(0,4).map(({id, label:navLabel, Icon}) => <button key={id} onClick={() => { setScreen(id); setMore(false); }} className={`flex flex-col items-center gap-1 text-[10px] font-bold ${screen === id ? "text-violet-600" : "text-slate-500 dark:text-slate-400"}`}><Icon size={19}/>{navLabel}</button>)}<button onClick={() => setMore(!more)} className="flex flex-col items-center gap-1 text-[10px] font-bold text-slate-500 dark:text-slate-400">{more ? <X size={19}/> : <Menu size={19}/>}More</button></nav>
    {more && <div className="fixed bottom-16 right-3 z-50 w-48 rounded-2xl border border-slate-200 bg-white p-2 shadow-xl dark:border-slate-700 dark:bg-slate-900 lg:hidden">{nav.slice(4).map(({id, label:navLabel, Icon}) => <button key={id} onClick={() => { setScreen(id); setMore(false); }} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-bold hover:bg-slate-100 dark:hover:bg-slate-800"><Icon size={17}/>{navLabel}</button>)}</div>}
  </main></div>;
}

function HomePage({ state, overall, mastery, choose, review }:{ state:LearningState; overall:number; mastery:(id:TopicId)=>number; choose:(id:TopicId)=>void; review:()=>void }) {
  const due = dueReview(state); const next = phaseOneTopics.find((topic) => mastery(topic.id) < 70) || phaseOneTopics[0]; const weakest = phaseOneTopics.slice().sort((a,b) => mastery(a.id) - mastery(b.id))[0];
  return <div className="space-y-7"><section className="rounded-[2rem] bg-slate-950 p-7 text-white sm:p-9"><p className="inline-flex items-center gap-2 rounded-full bg-violet-400/15 px-3 py-1 text-xs font-bold text-violet-200"><Sparkles size={14}/>Phase 1 — Mathematical Foundations</p><h2 className="mt-5 max-w-3xl text-3xl font-black tracking-tight sm:text-5xl">Understand the mathematics before you use it in quant finance.</h2><p className="mt-4 max-w-2xl leading-7 text-slate-300">Visualize it, experiment with it, then solve it. Mastery grows from evidence across concepts and difficulties.</p><button onClick={() => choose(next.id)} className="mt-7 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 font-bold text-slate-900">Continue: {next.title}<ChevronRight size={18}/></button><div className="mt-8 max-w-md"><div className="flex justify-between text-sm font-bold"><span>Phase 1 concept mastery</span><span>{overall}%</span></div><Progress value={overall} className="mt-3 h-3 bg-white/15 [&_[data-slot=progress-indicator]]:bg-emerald-400"/></div></section><div className="grid gap-4 sm:grid-cols-3"><Card title="Recommended next" value={next.title} text={`Reason: ${label(mastery(next.id))} evidence so far.`}/><Card title="Review due" value={`${due.length} concept${due.length === 1 ? "" : "s"}`} text={due.length ? "Strengthen a missed idea before it fades." : "Nothing due right now."} action={review}/><Card title="Weakest topic" value={weakest.title} text={`${mastery(weakest.id)}% current evidence`}/></div><section><Title kicker="Learning path" title="Eight topics. Many concepts inside each."/><div className="mt-5 grid gap-3 md:grid-cols-2">{phaseOneTopics.map((topic) => <button key={topic.id} onClick={() => choose(topic.id)} className="flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-4 text-left shadow-sm transition hover:border-violet-300 dark:border-slate-800 dark:bg-slate-900"><div className="grid h-11 w-11 place-items-center rounded-xl text-lg font-black text-white" style={{backgroundColor:topic.color}}>{topic.number}</div><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><p className="font-bold">{topic.title}</p><span className="text-xs font-bold text-slate-400">{mastery(topic.id)}%</span></div><p className="mt-1 truncate text-sm text-slate-500">{topic.concepts.length} concepts · {topic.short}</p><Progress value={mastery(topic.id)} className="mt-3 h-1.5"/></div></button>)}</div></section></div>;
}
function Card({title, value, text, action}:{title:string; value:string; text:string; action?:()=>void}) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p className="text-xs font-bold uppercase tracking-wider text-violet-600">{title}</p><p className="mt-2 text-lg font-black">{value}</p><p className="mt-2 text-sm text-slate-500">{text}</p>{action && <button onClick={action} className="mt-3 text-sm font-bold text-violet-700 dark:text-violet-300">Start review →</button>}</div>; }

function LessonPage({topicId, mastery, choose, record}:{topicId:TopicId; mastery:number; choose:(id:TopicId)=>void; record:(question:Question, correct:boolean, source:Source)=>void}) {
  const topic = topicById[topicId]; const [tab, setTab] = useState("intuition"); const [conceptId, setConceptId] = useState(topic.concepts[0].id); const concept = topic.concepts.find((item) => item.id === conceptId) || topic.concepts[0]; const index = phaseOneTopics.findIndex((item) => item.id === topicId);
  return <div><div className="flex flex-wrap justify-between gap-4"><div><p className="text-sm font-bold text-violet-600">Topic {topic.number} · {topic.concepts.length} concepts</p><h2 className="mt-1 text-3xl font-black sm:text-4xl">{topic.title}</h2><p className="mt-2 text-slate-500">{topic.description}</p></div><div className="w-48 rounded-xl bg-white p-3 shadow-sm dark:bg-slate-900"><div className="flex justify-between text-xs font-bold"><span>Topic mastery</span><span>{mastery}%</span></div><Progress value={mastery} className="mt-2"/></div></div><div className="mt-6 flex gap-2 overflow-x-auto rounded-xl bg-white p-1.5 shadow-sm dark:bg-slate-900">{["intuition","explore","learn","practice","quant","test"].map((item) => <button key={item} onClick={() => setTab(item)} className={`rounded-lg px-4 py-2 text-sm font-bold capitalize ${tab === item ? "bg-violet-600 text-white" : "text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800"}`}>{item}</button>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[240px_1fr]"><aside className="rounded-2xl border border-slate-200 bg-white p-3 dark:border-slate-800 dark:bg-slate-900"><p className="px-2 py-2 text-xs font-bold uppercase tracking-wider text-slate-500">Concepts</p>{topic.concepts.map((item, i) => <button key={item.id} onClick={() => setConceptId(item.id)} className={`w-full rounded-xl px-3 py-2.5 text-left text-sm ${conceptId === item.id ? "bg-violet-50 font-bold text-violet-800 dark:bg-violet-950/30 dark:text-violet-200" : "text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800"}`}><span className="mr-2 text-slate-400">{i + 1}.</span>{item.title}</button>)}</aside><div>{tab === "intuition" && <ConceptCard concept={concept}/>} {tab === "explore" && <LabFor topic={topicId}/>} {tab === "learn" && <Worked concept={concept}/>} {tab === "practice" && <PracticeSession key={topicId} topicId={topicId} record={record}/>} {tab === "quant" && <QuantCard topicId={topicId} text={concept.quant}/>} {tab === "test" && <MiniTest topicId={topicId} record={record}/>}</div></div><div className="mt-8 flex justify-between"><button disabled={index === 0} onClick={() => choose(phaseOneTopics[Math.max(0,index - 1)].id)} className="inline-flex items-center gap-1 rounded-lg px-3 py-2 font-bold text-slate-600 disabled:opacity-30"><ChevronLeft size={18}/>Previous</button><button disabled={index === phaseOneTopics.length - 1} onClick={() => choose(phaseOneTopics[Math.min(phaseOneTopics.length - 1,index + 1)].id)} className="inline-flex items-center gap-1 rounded-lg bg-slate-900 px-4 py-2 font-bold text-white disabled:opacity-30">Next<ChevronRight size={18}/></button></div></div>;
}
function ConceptCard({concept}:{concept:typeof phaseOneTopics[number]["concepts"][number]}) { return <section className="rounded-[1.7rem] bg-white p-6 shadow-sm dark:bg-slate-900 sm:p-8"><p className="text-xs font-bold uppercase tracking-wider text-violet-600">Visualization → intuition</p><h3 className="mt-2 text-2xl font-black">{concept.title}</h3><p className="mt-4 text-lg leading-8 text-slate-600 dark:text-slate-300">{concept.intuition}</p><div className="mt-6 rounded-xl border-l-4 border-violet-500 bg-violet-50 p-4 text-sm text-violet-950 dark:bg-violet-950/30 dark:text-violet-100"><b>Why does this exist?</b><br/>{concept.why}</div><div className="mt-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-950 dark:bg-rose-950/30 dark:text-rose-100"><b>Common mistake:</b> {concept.commonMistake}</div></section>; }
function Worked({concept}:{concept:typeof phaseOneTopics[number]["concepts"][number]}) { return <section className="rounded-[1.7rem] bg-white p-6 shadow-sm dark:bg-slate-900 sm:p-8"><p className="text-xs font-bold uppercase tracking-wider text-violet-600">Mathematics → worked example</p><h3 className="mt-2 text-2xl font-black">{concept.title}</h3><div className="mt-6 space-y-3">{concept.workedExample.map((step, i) => <div key={step} className="flex items-center gap-4 rounded-xl bg-slate-50 p-4 text-lg font-black dark:bg-slate-800"><span className="grid h-7 w-7 place-items-center rounded-full bg-violet-600 text-xs text-white">{i + 1}</span>{step}</div>)}</div><p className="mt-6 rounded-xl border border-slate-200 p-4 text-sm text-slate-600 dark:border-slate-700 dark:text-slate-300"><b>Why a quant cares:</b> {concept.quant}</p></section>; }
function LabFor({topic}:{topic:TopicId}) { const labs:Record<TopicId,React.ReactNode> = {order:<OrderMachine/>, fractions:<FractionLab/>, decimals:<DecimalLab/>, percentages:<PercentageLab/>, ratios:<RatioLab/>, negatives:<NumberLineLab/>, exponents:<ExponentLab/>, roots:<RootLab/>}; return <>{labs[topic]}</>; }
function QuantCard({topicId, text}:{topicId:TopicId; text:string}) { return <section className="rounded-[1.7rem] bg-slate-950 p-6 text-white sm:p-8"><p className="text-xs font-bold uppercase tracking-wider text-amber-300">Quant connection</p><h3 className="mt-2 text-2xl font-black">{topicById[topicId].title} in a trading calculation</h3><p className="mt-4 max-w-2xl text-lg leading-8 text-slate-300">{text}</p>{topicId === "percentages" ? <div className="mt-6"><MarketReturnLab/></div> : <p className="mt-6 rounded-xl bg-white/10 p-4 text-sm text-slate-200">This concept becomes one reliable building block of position sizing, P/L, returns, or risk analysis.</p>}</section>; }

function PracticePage({defaultTopic, record}:{defaultTopic:TopicId; record:(question:Question, correct:boolean, source:Source)=>void}) { const [topic, setTopic] = useState<TopicId>(defaultTopic); const [difficulty, setDifficulty] = useState<Difficulty>("beginner"); return <div><Title kicker="Practice room" title="Real sessions, not repeated cosmetic cards" text="Each session creates validated questions. Use fractions, decimals, and percentage signs naturally."/><div className="mt-6 flex flex-wrap gap-2">{phaseOneTopics.map((item) => <button key={item.id} onClick={() => setTopic(item.id)} className={`rounded-full px-3 py-2 text-sm font-bold ${topic === item.id ? "bg-violet-600 text-white" : "bg-white text-slate-600 shadow-sm dark:bg-slate-900 dark:text-slate-300"}`}>{item.number}. {item.title}</button>)}</div><div className="mt-5 flex gap-2">{(["beginner","intermediate","mastery"] as Difficulty[]).map((item) => <button key={item} onClick={() => setDifficulty(item)} className={`rounded-xl px-4 py-2 text-sm font-bold capitalize ${difficulty === item ? "bg-slate-900 text-white" : "bg-slate-200 text-slate-600 dark:bg-slate-800 dark:text-slate-300"}`}>{item}</button>)}</div><PracticeSession key={`${topic}-${difficulty}`} topicId={topic} difficulty={difficulty} record={record}/></div>; }
function PracticeSession({topicId, difficulty = "beginner", record}:{topicId:TopicId; difficulty?:Difficulty; record:(question:Question, correct:boolean, source:Source)=>void}) { const [questions, setQuestions] = useState<Question[]>(() => generateSession(topicId, difficulty, 10)); const [at, setAt] = useState(0); const [input, setInput] = useState(""); const [feedback, setFeedback] = useState<boolean | null>(null); const question = questions[at]; const submit = () => { const correct = answersMatch(input, question); record(question, correct, "practice"); setFeedback(correct); }; const next = () => { if (at === questions.length - 1) { setQuestions(generateSession(topicId, difficulty, 10)); setAt(0); } else setAt((old) => old + 1); setInput(""); setFeedback(null); }; return <section className="mt-6 rounded-[1.7rem] border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex justify-between text-sm font-bold"><span>{difficulty} practice</span><span>{at + 1}/{questions.length}</span></div><Progress value={(at / questions.length) * 100} className="mt-3"/><p className="mt-7 text-xl font-black">{question.prompt}</p><p className="mt-2 text-sm text-slate-500">Concept: {question.conceptId.split(".").slice(1).join(" ")}</p><AnswerInput input={input} setInput={setInput} submit={submit} disabled={feedback !== null}/>{feedback === null ? <button onClick={submit} className="ml-3 rounded-xl bg-violet-600 px-5 py-3 font-bold text-white">Check answer</button> : <><div className={`mt-5 rounded-xl p-4 ${feedback ? "bg-emerald-50 text-emerald-950 dark:bg-emerald-950/30 dark:text-emerald-100" : "bg-amber-50 text-amber-950 dark:bg-amber-950/30 dark:text-amber-100"}`}><p className="font-black">{feedback ? "Correct — you earned evidence for this concept." : "Not quite — this concept is now scheduled for review."}</p><ol className="mt-2 list-decimal space-y-1 pl-5 text-sm">{question.explanation.map((step) => <li key={step}>{step}</li>)}</ol><p className="mt-3 text-sm"><b>Similar thought:</b> {question.hint}</p></div><button onClick={next} className="mt-4 rounded-xl bg-slate-900 px-5 py-3 font-bold text-white">{at === questions.length - 1 ? "New session" : "Next question"}</button></>}</section>; }
function AnswerInput({input, setInput, submit, disabled = false}:{input:string; setInput:(value:string)=>void; submit:()=>void; disabled?:boolean}) { return <input aria-label="Your answer" value={input} disabled={disabled} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => event.key === "Enter" && !disabled && submit()} placeholder="Your answer" className="mt-5 w-48 rounded-xl border border-slate-300 bg-white px-4 py-3 text-lg font-bold outline-none focus:border-violet-500 disabled:opacity-60 dark:border-slate-700 dark:bg-slate-950 dark:text-white"/>; }
function MiniTest({topicId, record}:{topicId:TopicId; record:(question:Question, correct:boolean, source:Source)=>void}) { const [questions] = useState(() => Array.from({length:6}, (_, index) => generateQuestion(topicId, (["beginner","intermediate","mastery"] as Difficulty[])[index % 3]))); return <Assessment questions={questions} source="test" record={record} label="Mini test"/>; }

function VisualPage() { const [lab, setLab] = useState<TopicId>("fractions"); return <div><Title kicker="Visual lab" title="Free experimentation" text="Choose a laboratory. Every control updates the mathematical representation immediately."/><div className="mt-6 flex flex-wrap gap-2">{phaseOneTopics.map((topic) => <button key={topic.id} onClick={() => setLab(topic.id)} className={`rounded-full px-3 py-2 text-sm font-bold ${lab === topic.id ? "bg-violet-600 text-white" : "bg-white text-slate-600 shadow-sm dark:bg-slate-900 dark:text-slate-300"}`}>{topic.title}</button>)}</div><div className="mt-6"><LabFor topic={lab}/></div></div>; }
function TestsPage({record, setState}:{record:(question:Question, correct:boolean, source:Source)=>void; setState:React.Dispatch<React.SetStateAction<LearningState>>}) { const [mode, setMode] = useState<"diagnostic" | "final">("diagnostic"); const [seed, setSeed] = useState(0); const questions = mode === "final" ? generateFinalTest() : Array.from({length:16}, (_, index) => generateQuestion(phaseOneTopics[index % 8].id, (["beginner","intermediate"] as Difficulty[])[index % 2])); const reset = (next:"diagnostic" | "final") => { setMode(next); setSeed((old) => old + 1); }; return <div><Title kicker={mode === "final" ? "Phase 1 final test" : "Start diagnostic"} title={mode === "final" ? "32 mixed questions" : "Find your starting point"} text={mode === "final" ? "A randomized assessment across all eight topics." : "This creates a performance-based recommended path."}/><div className="mt-5 flex gap-2"><button onClick={() => reset("diagnostic")} className={`rounded-xl px-3 py-2 font-bold ${mode === "diagnostic" ? "bg-violet-600 text-white" : "bg-white dark:bg-slate-900"}`}>Diagnostic</button><button onClick={() => reset("final")} className={`rounded-xl px-3 py-2 font-bold ${mode === "final" ? "bg-violet-600 text-white" : "bg-white dark:bg-slate-900"}`}>Final test</button></div><Assessment key={`${mode}-${seed}`} questions={questions} source={mode === "final" ? "test" : "diagnostic"} record={record} label={mode === "final" ? "Final test" : "Diagnostic"} onComplete={(scores) => { if (mode === "final") { const score = Math.round((Object.values(scores).reduce((sum, item) => sum + item.correct, 0) / questions.length) * 100); setState((old) => ({ ...old, finalTest:{completedAt:Date.now(), score, passed:score >= 80} })); } else { const scoresByTopic = Object.fromEntries(phaseOneTopics.map((topic) => [topic.id, Math.round(((scores[topic.id]?.correct || 0) / (scores[topic.id]?.total || 1)) * 100)])) as Record<TopicId, number>; setState((old) => ({ ...old, diagnostic:{completedAt:Date.now(), scores:scoresByTopic} })); } }}/></div>; }
function Assessment({questions, source, record, label:assessmentLabel, onComplete}:{questions:Question[]; source:Source; record:(question:Question, correct:boolean, source:Source)=>void; label:string; onComplete?:(scores:Record<TopicId,{correct:number;total:number}>)=>void}) { const [at, setAt] = useState(0); const [input, setInput] = useState(""); const [scores, setScores] = useState<Record<TopicId,{correct:number;total:number}>>({} as Record<TopicId,{correct:number;total:number}>); const [complete, setComplete] = useState(false); const question = questions[at]; const submit = () => { const correct = answersMatch(input, question); record(question, correct, source); const updated = {...scores, [question.topicId]:{correct:(scores[question.topicId]?.correct || 0) + (correct ? 1 : 0), total:(scores[question.topicId]?.total || 0) + 1}}; setScores(updated); if (at === questions.length - 1) { setComplete(true); onComplete?.(updated); } else { setAt((old) => old + 1); setInput(""); } }; if (complete) return <Result label={assessmentLabel} scores={scores}/>; return <section className="mt-6 rounded-[1.7rem] bg-white p-6 shadow-sm dark:bg-slate-900"><p className="text-xs font-bold uppercase tracking-wider text-violet-600">{assessmentLabel} · {at + 1}/{questions.length}</p><Progress value={(at / questions.length) * 100} className="mt-3"/><p className="mt-6 text-xl font-black">{question.prompt}</p><AnswerInput input={input} setInput={setInput} submit={submit}/><button onClick={submit} className="ml-3 rounded-xl bg-violet-600 px-5 py-3 font-bold text-white">Submit</button></section>; }
function Result({label:resultLabel, scores}:{label:string; scores:Record<TopicId,{correct:number;total:number}>}) { const correct = Object.values(scores).reduce((sum, score) => sum + score.correct, 0); const total = Object.values(scores).reduce((sum, score) => sum + score.total, 0); return <div className="mt-6"><Title kicker={`${resultLabel} complete`} title={`${correct}/${total} correct`} text="Topic detail is more useful than one overall number."/><div className="mt-6 grid gap-3 sm:grid-cols-2">{phaseOneTopics.map((topic) => { const score = scores[topic.id] || {correct:0,total:0}; const percent = score.total ? Math.round((score.correct / score.total) * 100) : 0; return <div key={topic.id} className="rounded-xl bg-white p-4 shadow-sm dark:bg-slate-900"><div className="flex justify-between font-bold"><span>{topic.title}</span><span>{percent}%</span></div><Progress value={percent} className="mt-3"/><p className="mt-2 text-sm text-slate-500">{percent < 70 ? "Practice the related concepts next." : "A solid result—keep the evidence fresh."}</p></div>; })}</div></div>; }
function ProgressPage({state, mastery}:{state:LearningState; mastery:(id:TopicId)=>number}) { const complete = phaseOneTopics.every((topic) => mastery(topic.id) >= 70) && Boolean(state.finalTest?.passed); return <div><Title kicker="Progress map" title="Concept-level evidence" text="A topic cannot become mastered just by repeating a single easy question."/><div className="mt-6 space-y-4">{phaseOneTopics.map((topic) => <details key={topic.id} className="rounded-2xl bg-white p-5 shadow-sm dark:bg-slate-900"><summary className="flex cursor-pointer items-center justify-between font-black"><span>{topic.title}</span><span style={{color:topic.color}}>{mastery(topic.id)}% · {label(mastery(topic.id))}</span></summary><div className="mt-5 grid gap-2 sm:grid-cols-2">{topic.concepts.map((concept) => { const score = state.conceptProgress[concept.id]?.mastery || 0; return <div key={concept.id} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><div className="flex justify-between text-sm font-bold"><span>{concept.title}</span><span>{score}%</span></div><Progress value={score} className="mt-2 h-1.5"/></div>; })}</div></details>)}</div><section className={`mt-7 rounded-[2rem] p-7 text-white ${complete ? "bg-emerald-600" : "bg-slate-950"}`}><p className="text-xs font-bold uppercase tracking-wider text-emerald-100">Phase 1 completion</p><h3 className="mt-2 text-3xl font-black">{complete ? "Mathematical Foundations Complete" : "Still building evidence"}</h3><p className="mt-3 text-slate-200">{complete ? "Next preview: Phase 2 — Algebra & Functions." : "Completion requires every topic at least Strong and a final-test score of 80% or higher."}</p></section></div>; }
function Title({kicker, title, text}:{kicker:string; title:string; text?:string}) { return <div><p className="text-xs font-bold uppercase tracking-[.16em] text-violet-600">{kicker}</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">{title}</h2>{text && <p className="mt-3 max-w-2xl leading-7 text-slate-500 dark:text-slate-400">{text}</p>}</div>; }
