"use client";

import { useEffect, useState } from "react";
import { BarChart3, BookOpen, Brain, Calculator, ChevronLeft, ChevronRight, CircleHelp, FlaskConical, Home, Moon, Play, Sparkles, Sun, Target, Trophy } from "lucide-react";
import { Progress } from "@/components/ui/progress";
import { topics, topicById, type TopicId } from "@/lib/lesson-data";
import { DecimalLab, ExponentLab, FractionLab, MarketReturnLab, NumberLineLab, OrderMachine, PercentageLab, RatioLab, RootLab } from "@/components/math-labs";

type Screen = "home" | "learn" | "practice" | "visual" | "quant" | "tests" | "progress";
const nav: { id: Screen; label: string; icon: typeof Home }[] = [
  { id: "home", label: "Home", icon: Home }, { id: "learn", label: "Learn", icon: BookOpen }, { id: "practice", label: "Practice", icon: Target }, { id: "visual", label: "Visual Lab", icon: FlaskConical }, { id: "quant", label: "Quant Lab", icon: Calculator }, { id: "tests", label: "Tests", icon: Trophy }, { id: "progress", label: "Progress", icon: BarChart3 },
];

export default function Page() {
  const [screen, setScreen] = useState<Screen>("home");
  const [topicId, setTopicId] = useState<TopicId>("order");
  const [dark, setDark] = useState(false);
  const [showWelcome, setShowWelcome] = useState(false);
  const [mastery, setMastery] = useState<Record<TopicId, number>>(() => Object.fromEntries(topics.map((t, i) => [t.id, i === 0 ? 22 : 0])) as Record<TopicId, number>);
  const [review, setReview] = useState<string[]>([]);
  useEffect(() => { const saved = localStorage.getItem("quantmath-phase1"); if (saved) { const data = JSON.parse(saved); if (data.mastery) setMastery(data.mastery); if (data.review) setReview(data.review); if (data.last) setTopicId(data.last); } else setShowWelcome(true); }, []);
  useEffect(() => { localStorage.setItem("quantmath-phase1", JSON.stringify({ mastery, review, last: topicId })); }, [mastery, review, topicId]);
  const progress = Math.round(Object.values(mastery).reduce((a, b) => a + b, 0) / topics.length);
  const chooseTopic = (id: TopicId) => { setTopicId(id); setScreen("learn"); };
  const markResult = (id: TopicId, correct: boolean, weakness: string) => { setMastery((prev) => ({ ...prev, [id]: Math.max(0, Math.min(100, prev[id] + (correct ? 12 : -2))) })); setReview((prev) => correct ? prev.filter((x) => x !== weakness) : Array.from(new Set([...prev, weakness]))); };
  useEffect(() => {
    type ModelContext = { registerTool: (tool: { name: string; title: string; description: string; inputSchema: object; annotations?: object; execute: (input: unknown) => unknown }, options: { signal: AbortSignal }) => void | Promise<void> };
    const context = (document as Document & { modelContext?: ModelContext }).modelContext;
    if (!context) return;
    const lifecycle = new AbortController();
    const statusTool = { name: "get_quantmath_progress", title: "Get QuantMath progress", description: "Read the learner's current Phase 1 mastery and review count.", inputSchema: { type: "object", properties: {}, additionalProperties: false }, annotations: { readOnlyHint: true }, execute: () => ({ phase: 1, progress, reviewCount: review.length, mastery }) };
    const lessonTool = { name: "open_quantmath_lesson", title: "Open a QuantMath lesson", description: "Open one Phase 1 topic in the same way as selecting it in the learning path.", inputSchema: { type: "object", properties: { topic: { type: "string", enum: topics.map(t => t.id) } }, required: ["topic"], additionalProperties: false }, execute: (input: unknown) => { const topic = typeof input === "object" && input !== null ? (input as { topic?: unknown }).topic : undefined; if (typeof topic !== "string" || !topics.some(t => t.id === topic)) throw new Error("Choose a valid Phase 1 topic."); chooseTopic(topic as TopicId); return { opened: topic }; } };
    void Promise.resolve(context.registerTool(statusTool, { signal: lifecycle.signal })).catch(() => undefined);
    void Promise.resolve(context.registerTool(lessonTool, { signal: lifecycle.signal })).catch(() => undefined);
    return () => lifecycle.abort();
  }, [progress, review.length, mastery]);
  return <div className={dark ? "dark" : ""}><main className="min-h-screen bg-[#f6f7fb] text-slate-900 dark:bg-slate-950 dark:text-slate-50">
    <Sidebar screen={screen} setScreen={setScreen} progress={progress} />
    <div className="pb-24 lg:pl-72 lg:pb-10"><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-slate-200/80 bg-[#f6f7fb]/90 px-4 backdrop-blur dark:border-slate-800 dark:bg-slate-950/90 sm:px-8"><div className="flex items-center gap-2 text-sm text-slate-500"><span className="hidden sm:inline">Phase 1</span><span className="h-1 w-1 rounded-full bg-slate-400"/><span>{screen === "learn" ? topicById[topicId].title : nav.find(n=>n.id===screen)?.label}</span></div><button onClick={()=>setDark(!dark)} className="rounded-xl border border-slate-200 bg-white p-2.5 text-slate-600 shadow-sm dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300" aria-label="Toggle color mode">{dark?<Sun size={18}/>:<Moon size={18}/>}</button></header>
      <div className="mx-auto max-w-6xl px-4 py-6 sm:px-8 sm:py-9">{screen === "home" && <HomeScreen progress={progress} mastery={mastery} review={review} onTopic={chooseTopic} onReview={()=>setScreen("practice")} />}{screen === "learn" && <LessonScreen topicId={topicId} mastery={mastery[topicId]} onTopic={chooseTopic} onResult={markResult}/>} {screen === "practice" && <PracticeScreen topicId={topicId} onTopic={setTopicId} onResult={markResult} review={review}/>} {screen === "visual" && <VisualScreen/>}{screen === "quant" && <QuantScreen/>}{screen === "tests" && <TestScreen mastery={mastery} setMastery={setMastery} setReview={setReview}/>} {screen === "progress" && <ProgressScreen mastery={mastery} progress={progress} review={review}/>}</div>
    </div>{showWelcome && <Welcome onClose={()=>setShowWelcome(false)}/>}</main></div>;
}

function Sidebar({screen,setScreen,progress}:{screen:Screen;setScreen:(s:Screen)=>void;progress:number}) { return <><aside className="fixed inset-y-0 left-0 z-30 hidden w-72 border-r border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900 lg:flex lg:flex-col"><Brand/><nav className="mt-8 space-y-1">{nav.map(({id,label,icon:Icon})=><button key={id} onClick={()=>setScreen(id)} className={`flex w-full items-center gap-3 rounded-xl px-3.5 py-3 text-left text-sm font-bold transition ${screen===id?"bg-violet-600 text-white shadow-lg shadow-violet-200 dark:shadow-none":"text-slate-500 hover:bg-slate-100 hover:text-slate-900 dark:text-slate-400 dark:hover:bg-slate-800 dark:hover:text-white"}`}><Icon size={18}/>{label}</button>)}</nav><div className="mt-auto rounded-2xl bg-slate-950 p-4 text-white"><p className="text-xs font-bold uppercase tracking-wider text-violet-200">Phase 1</p><p className="mt-1 font-bold">Mathematical Foundations</p><Progress value={progress} className="mt-4 h-2 [&_[data-slot=progress-indicator]]:bg-violet-400"/><p className="mt-2 text-xs text-slate-300">{progress}% explored</p></div></aside><nav className="fixed inset-x-0 bottom-0 z-40 grid grid-cols-5 border-t border-slate-200 bg-white/95 px-1 py-2 backdrop-blur dark:border-slate-800 dark:bg-slate-900/95 lg:hidden">{nav.slice(0,5).map(({id,label,icon:Icon})=><button key={id} onClick={()=>setScreen(id)} className={`flex flex-col items-center gap-1 py-1 text-[10px] font-bold ${screen===id?"text-violet-600":"text-slate-500 dark:text-slate-400"}`}><Icon size={19}/>{label}</button>)}</nav></> }
function Brand(){return <div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-violet-600 text-xl font-black text-white">∑</div><div><h1 className="font-black tracking-tight">QuantMath</h1><p className="text-xs text-slate-500">Learn by seeing</p></div></div>}

function HomeScreen({progress,mastery,review,onTopic,onReview}:{progress:number;mastery:Record<TopicId,number>;review:string[];onTopic:(id:TopicId)=>void;onReview:()=>void}){return <div className="space-y-7"><section className="overflow-hidden rounded-[2rem] bg-slate-950 p-6 text-white sm:p-9"><div className="max-w-2xl"><p className="inline-flex items-center gap-2 rounded-full bg-violet-400/15 px-3 py-1 text-xs font-bold text-violet-200"><Sparkles size={14}/> Phase 1 — Mathematical Foundations</p><h2 className="mt-5 text-3xl font-black tracking-tight sm:text-5xl">Build the math you need for quantitative finance — visually.</h2><p className="mt-4 max-w-xl text-base leading-7 text-slate-300">No formula dumping. Touch the ideas first, then learn the notation, solve it, and use it in a market example.</p><button onClick={()=>onTopic(topics.find(t=>mastery[t.id]<70)?.id ?? "order")} className="mt-7 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 font-bold text-slate-900">Continue learning <ChevronRight size={18}/></button></div><div className="mt-8 max-w-md"><div className="flex justify-between text-sm font-bold"><span>Your Phase 1 progress</span><span>{progress}%</span></div><Progress value={progress} className="mt-3 h-3 bg-white/15 [&_[data-slot=progress-indicator]]:bg-emerald-400"/></div></section>
    {review.length>0&&<button onClick={onReview} className="flex w-full items-center justify-between rounded-2xl border border-amber-200 bg-amber-50 p-5 text-left dark:border-amber-900 dark:bg-amber-950/30"><div><p className="font-black text-amber-900 dark:text-amber-200">Review {review.length} concept{review.length>1?"s":""}</p><p className="mt-1 text-sm text-amber-800 dark:text-amber-300">A missed answer becomes a short focused review.</p></div><Play className="text-amber-700"/></button>}
    <section><SectionTitle kicker="Your learning path" title="Eight ideas, connected"/><div className="mt-5 grid gap-3 md:grid-cols-2">{topics.map((topic,index)=><button key={topic.id} onClick={()=>onTopic(topic.id)} className="group flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-violet-300 hover:shadow-md dark:border-slate-800 dark:bg-slate-900"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl text-lg font-black text-white" style={{backgroundColor:topic.color}}>{topic.number}</div><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><p className="font-bold">{topic.title}</p><span className="text-xs font-bold text-slate-400">{mastery[topic.id]}%</span></div><p className="mt-1 truncate text-sm text-slate-500">{topic.short}</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full" style={{width:`${mastery[topic.id]}%`,backgroundColor:topic.color}}/></div></div>{index<topics.length-1&&<ChevronRight className="text-slate-300 group-hover:text-violet-500" size={18}/>}</button>)}</div></section></div>}

function LessonScreen({topicId,mastery,onTopic,onResult}:{topicId:TopicId;mastery:number;onTopic:(id:TopicId)=>void;onResult:(id:TopicId,c:boolean,w:string)=>void}) { const t=topicById[topicId]; const index=topics.findIndex(x=>x.id===topicId); const [tab,setTab]=useState("intuition"); return <div><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold text-violet-600">Topic {t.number} of 8</p><h2 className="mt-1 text-3xl font-black tracking-tight sm:text-4xl">{t.title}</h2><p className="mt-2 text-slate-500">Mastery: <b className="text-slate-800 dark:text-white">{mastery}%</b> · learn by experimenting</p></div><div className="w-full max-w-[13rem] rounded-xl bg-white p-3 shadow-sm dark:bg-slate-900"><div className="flex justify-between text-xs font-bold"><span>Current mastery</span><span>{mastery}%</span></div><Progress value={mastery} className="mt-2"/></div></div><div className="mt-7 overflow-x-auto"><div className="flex min-w-max gap-2 rounded-xl bg-white p-1.5 shadow-sm dark:bg-slate-900">{["intuition","explore","learn","practice","quant","test"].map(x=><button key={x} onClick={()=>setTab(x)} className={`rounded-lg px-4 py-2 text-sm font-bold capitalize ${tab===x?"bg-violet-600 text-white":"text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800"}`}>{x}</button>)}</div></div><div className="mt-6">{tab==="intuition"&&<Intuition t={t} onExplore={()=>setTab("explore")}/>} {tab==="explore"&&<TopicLab id={topicId}/>} {tab==="learn"&&<LearnCard t={t}/>} {tab==="practice"&&<PracticeCard t={t} onResult={onResult}/>} {tab==="quant"&&<QuantCard t={t}/>} {tab==="test"&&<MiniTest t={t} onResult={onResult}/>}</div><div className="mt-8 flex justify-between"><button onClick={()=>onTopic(topics[Math.max(0,index-1)].id)} disabled={index===0} className="inline-flex items-center gap-1 rounded-lg px-3 py-2 text-sm font-bold text-slate-600 disabled:opacity-30"><ChevronLeft size={18}/> Previous</button><button onClick={()=>onTopic(topics[Math.min(topics.length-1,index+1)].id)} disabled={index===topics.length-1} className="inline-flex items-center gap-1 rounded-lg bg-slate-900 px-4 py-2 text-sm font-bold text-white disabled:opacity-30">Next <ChevronRight size={18}/></button></div></div> }
function Intuition({t,onExplore}:{t:typeof topics[number];onExplore:()=>void}){return <section className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-[1.75rem] bg-white p-6 shadow-sm dark:bg-slate-900 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-violet-600">1. Intuition</p><h3 className="mt-3 text-2xl font-black">What is it, really?</h3><p className="mt-4 text-lg leading-8 text-slate-600 dark:text-slate-300">{t.intuition}</p><div className="mt-7 rounded-xl border-l-4 border-violet-500 bg-violet-50 p-4 text-sm text-violet-950 dark:bg-violet-950/30 dark:text-violet-100"><b>Why does it exist?</b><br/>{t.why}</div><button onClick={onExplore} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-violet-600 px-5 py-3 font-bold text-white">Show me visually <ChevronRight size={18}/></button></div><div className="rounded-[1.75rem] p-7 text-white" style={{background:`linear-gradient(135deg, ${t.color}, #24243e)`}}><p className="text-xs font-bold uppercase tracking-[.16em] text-white/70">First thought</p><p className="mt-5 text-2xl font-black leading-tight">“I can change the numbers and see the rule.”</p><div className="mt-10 rounded-2xl bg-white/15 p-5"><p className="text-sm text-white/80">Not a formula to memorize. An idea you can test.</p></div></div></section>}
function LearnCard({t}:{t:typeof topics[number]}) { return <section className="rounded-[1.75rem] bg-white p-6 shadow-sm dark:bg-slate-900 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-violet-600">4. Mathematics, after the picture</p><h3 className="mt-3 text-2xl font-black">Now give the idea a compact name</h3><div className="mt-6 rounded-2xl bg-slate-50 p-6 text-center font-mono text-2xl font-black text-slate-800 dark:bg-slate-800 dark:text-white sm:text-3xl">{t.example}</div><div className="mt-6 grid gap-4 md:grid-cols-2"><InfoBox title="Why this rule works" text={t.why}/><InfoBox title="Common beginner mistake" text={mistakes[t.id]}/></div></section>}
const mistakes:Record<TopicId,string>={order:"Multiplication does not always come before division. They share priority, so go left to right.",fractions:"1/2 + 1/4 is not 2/6. Those pieces are different sizes.",decimals:"0.8 is not smaller than 0.75. Write it as 0.80 and compare.",percentages:"+10% then −10% is not zero overall. The second change starts from a different number.",ratios:"3:2 is a comparison between two parts. It is not 3/2 of the total.",negatives:"Subtracting a negative is not “more negative.” It means move right: 3 − (−2) = 5.",exponents:"2³ is 2 × 2 × 2, not 2 × 3.",roots:"√81 asks for a number multiplied by itself. It does not mean 81 ÷ 2."};
function InfoBox({title,text}:{title:string;text:string}){return <div className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><p className="font-bold">{title} <CircleHelp className="inline text-violet-500" size={15}/></p><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{text}</p></div>}
function TopicLab({id}:{id:TopicId}){ const labs:Record<TopicId,React.ReactNode>={order:<OrderMachine/>,fractions:<FractionLab/>,decimals:<DecimalLab/>,percentages:<PercentageLab/>,ratios:<RatioLab/>,negatives:<NumberLineLab/>,exponents:<ExponentLab/>,roots:<RootLab/>}; return <div>{labs[id]}</div> }
function PracticeCard({t,onResult}:{t:typeof topics[number];onResult:(id:TopicId,c:boolean,w:string)=>void}){return <div><SectionTitle kicker="6. Practice" title="Try it yourself"/><QuestionCard topic={t} onResult={onResult}/><div className="mt-5 grid gap-4 sm:grid-cols-3">{["Beginner","Intermediate","Mastery"].map((x,i)=><div key={x} className={`rounded-xl border p-4 ${i===0?"border-violet-300 bg-violet-50 dark:bg-violet-950/20":"border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"}`}><p className="font-bold">{x}</p><p className="mt-1 text-sm text-slate-500">{i===0?"Build confidence first.":i===1?"Mix two ideas together.":"Test your understanding."}</p></div>)}</div></div>}
function QuantCard({t}:{t:typeof topics[number]}) { return <section className="rounded-[1.75rem] bg-slate-950 p-6 text-white sm:p-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-amber-300">7. Quant connection</p><h3 className="mt-3 text-2xl font-black">Why does a quant care?</h3><p className="mt-4 max-w-2xl text-lg leading-8 text-slate-300">{t.quant}</p>{t.id==="percentages"?<div className="mt-7"><MarketReturnLab/></div>:<div className="mt-7 rounded-2xl bg-white/10 p-5"><p className="text-sm text-slate-200">This idea becomes one small, reliable part of a future calculation. The goal is to understand it well enough that your numbers make sense before any code is written.</p></div>}</section>}
function MiniTest({t,onResult}:{t:typeof topics[number];onResult:(id:TopicId,c:boolean,w:string)=>void}){return <div><SectionTitle kicker="8. Mini test" title="Check understanding"/><QuestionCard topic={t} onResult={onResult} test/></div>}
function QuestionCard({topic,onResult,test=false}:{topic:typeof topics[number];onResult:(id:TopicId,c:boolean,w:string)=>void;test?:boolean}){const [value,setValue]=useState("");const [submitted,setSubmitted]=useState(false); const correct=Number(value)===topic.practice.answer; const submit=()=>{setSubmitted(true);onResult(topic.id,correct,topic.practice.weakness)}; return <section className="mt-5 rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-7"><div className="flex justify-between"><p className="text-xs font-bold uppercase tracking-[.16em] text-violet-600">{test?"One quick check":"Practice question"}</p><span className="text-xs font-bold text-slate-400">No penalty for trying</span></div><p className="mt-4 text-xl font-black">{topic.practice.prompt}</p><div className="mt-5 flex flex-wrap gap-3"><input value={value} onChange={e=>{setValue(e.target.value);setSubmitted(false)}} onKeyDown={e=>e.key==="Enter"&&submit()} inputMode="decimal" aria-label="Your answer" placeholder="Your answer" className="w-40 rounded-xl border border-slate-300 bg-white px-4 py-3 text-lg font-bold outline-none focus:border-violet-500 dark:bg-slate-950 dark:text-white"/><button onClick={submit} className="rounded-xl bg-violet-600 px-5 py-3 font-bold text-white">Check answer</button></div>{submitted&&<div className={`mt-5 rounded-xl p-4 ${correct?"bg-emerald-50 text-emerald-950 dark:bg-emerald-950/30 dark:text-emerald-100":"bg-amber-50 text-amber-950 dark:bg-amber-950/30 dark:text-amber-100"}`}><p className="font-black">{correct?"Correct — nice work.":`Not quite. The answer is ${topic.practice.answer}.`}</p><p className="mt-1 text-sm">{topic.practice.explanation}</p><p className="mt-3 text-sm"><b>Similar thought:</b> {topic.practice.hint}</p></div>}</section>}

function VisualScreen(){return <div className="space-y-6"><SectionTitle kicker="Visual Lab" title="Experiment freely" text="No lesson order here. Pull a slider and watch what changes."/><div className="grid gap-6"><FractionLab/><PercentageLab/><NumberLineLab/><OrderMachine/><RatioLab/><ExponentLab/><RootLab/></div></div>}
function QuantScreen(){const [entry,setEntry]=useState(100),[stop,setStop]=useState(98),[target,setTarget]=useState(106),[wins,setWins]=useState(30),[losses,setLosses]=useState(20),[capital,setCapital]=useState(100),[rate,setRate]=useState(10),[periods,setPeriods]=useState(3);const risk=Math.abs(entry-stop),reward=Math.abs(target-entry),total=wins+losses,final=capital*(1+rate/100)**periods; return <div className="space-y-6"><SectionTitle kicker="Quant Lab" title="Why does a quant need this?" text="Small calculators built from the Phase 1 ideas."/><MarketReturnLab/><section className="grid gap-6 lg:grid-cols-2"><LabCard title="Risk / reward"><div className="grid grid-cols-3 gap-3"><NumberField label="Entry" value={entry} set={setEntry}/><NumberField label="Stop" value={stop} set={setStop}/><NumberField label="Target" value={target} set={setTarget}/></div><div className="mt-5 grid grid-cols-3 gap-3"><MetricLight label="Risk" value={fmt(risk)}/><MetricLight label="Reward" value={fmt(reward)}/><MetricLight label="R:R" value={`${fmt(reward/risk)} : 1`}/></div></LabCard><LabCard title="Win rate is not win/loss ratio"><div className="grid grid-cols-2 gap-3"><NumberField label="Wins" value={wins} set={setWins}/><NumberField label="Losses" value={losses} set={setLosses}/></div><div className="mt-5 grid grid-cols-3 gap-3"><MetricLight label="Total" value={String(total)}/><MetricLight label="Win rate" value={`${fmt(wins/total*100)}%`}/><MetricLight label="Win/loss" value={`${fmt(wins/losses)} : 1`}/></div></LabCard></section><LabCard title="Compounding calculator"><div className="grid gap-3 sm:grid-cols-3"><NumberField label="Starting capital" value={capital} set={setCapital}/><NumberField label="Return / period %" value={rate} set={setRate}/><NumberField label="Periods" value={periods} set={setPeriods}/></div><div className="mt-6 flex h-32 items-end gap-2 rounded-xl bg-slate-50 p-3 dark:bg-slate-800">{Array.from({length:Math.max(1,Math.min(12,periods))},(_,i)=>{const v=capital*(1+rate/100)**(i+1);return <div className="flex flex-1 flex-col justify-end" key={i}><div className="rounded-t bg-violet-500" style={{height:`${Math.max(8,(v/final)*100)}%`}}/><span className="mt-1 text-center text-[10px] text-slate-500">{i+1}</span></div>})}</div><p className="mt-4 text-lg font-black">Final capital: {fmt(final)}</p><p className="text-sm text-slate-500">{capital} × (1 + {rate/100})^{periods}</p></LabCard></div>}
function LabCard({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-[1.7rem] bg-white p-6 shadow-sm dark:bg-slate-900"><h3 className="text-xl font-black">{title}</h3><div className="mt-5">{children}</div></section>};function NumberField({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <label className="text-sm font-bold text-slate-600 dark:text-slate-300">{label}<input type="number" value={value} onChange={e=>set(Number(e.target.value))} className="mt-2 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-lg font-black text-slate-900 dark:border-slate-700 dark:bg-slate-950 dark:text-white"/></label>};function MetricLight({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-violet-50 p-3 dark:bg-violet-950/30"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-black">{value}</p></div>}
const fmt=(n:number)=>Number.isFinite(n)?n.toLocaleString(undefined,{maximumFractionDigits:2}):"—";

function PracticeScreen({topicId,onTopic,onResult,review}:{topicId:TopicId;onTopic:(id:TopicId)=>void;onResult:(id:TopicId,c:boolean,w:string)=>void;review:string[]}){const [selected,setSelected]=useState<TopicId>(topicId);const topic=topicById[selected];return <div><SectionTitle kicker="Practice room" title="Small tries build strong intuition" text={review.length?`Your review queue has ${review.length} idea${review.length>1?"s":""}. Start wherever you need it.`:"Pick a topic. You can repeat any exercise."}/><div className="mt-6 flex flex-wrap gap-2">{topics.map(t=><button key={t.id} onClick={()=>{setSelected(t.id);onTopic(t.id)}} className={`rounded-full px-3 py-2 text-sm font-bold ${selected===t.id?"bg-violet-600 text-white":"bg-white text-slate-600 shadow-sm dark:bg-slate-900 dark:text-slate-300"}`}>{t.number}. {t.title}</button>)}</div><QuestionCard topic={topic} onResult={onResult}/><div className="mt-6 rounded-2xl bg-slate-900 p-6 text-white"><p className="text-xs font-bold uppercase tracking-widest text-violet-200">How mastery works</p><p className="mt-2 font-bold">Concept exercises 20% · Practice 35% · Topic test 45%</p><p className="mt-2 text-sm text-slate-300">We use recent performance, not just completion. Retake anything anytime.</p></div></div>}
const finalQuestions: {topic:TopicId; prompt:string; answer:number; weakness:string}[] = [
  ["order","What is 8 + 6 × 4?",32],["order","What is (12 − 3) × 2?",18],["order","What is 18 ÷ 3 × 2?",12],["order","What is 2 + 3² × 4?",38],
  ["fractions","What is 1/2 + 1/4 as a decimal?",.75],["fractions","What is 3/4 − 1/4?",.5],["fractions","What is 1/2 × 1/3?",1/6],["fractions","How many 1/4 pieces fit inside 1/2?",2],
  ["decimals","Which is larger: 0.8 or 0.75? Enter it.",.8],["decimals","What is 0.4 + 0.06?",.46],["decimals","Round 3.476 to two decimal places.",3.48],["decimals","Write 75 hundredths as a decimal.",.75],
  ["percentages","200 becomes 230. Percentage increase?",15],["percentages","What is 37% as a decimal?",.37],["percentages","What is 10% of 250?",25],["percentages","100 falls 10%. New value?",90],
  ["ratios","If 3/5 = 12/x, what is x?",20],["ratios","Simplify 30:20. Enter the first number in the simplified ratio.",3],["ratios","30 wins and 20 losses: win rate %?",60],["ratios","Risk 2 and reward 6: reward/risk?",3],
  ["negatives","What is −3 + 5?",2],["negatives","What is 3 − 7?",-4],["negatives","What is −2 × 3?",-6],["negatives","What is −2 × −4?",8],
  ["exponents","What is 2³?",8],["exponents","What is 10²?",100],["exponents","What is 2⁻² as a decimal?",.25],
  ["roots","What is √81?",9],["roots","What is √49?",7],["roots","Which whole number is √50 closest to?",7],
].map(([topic,prompt,answer]) => ({topic:topic as TopicId,prompt:prompt as string,answer:answer as number,weakness:topicById[topic as TopicId].practice.weakness}));
function TestScreen({mastery,setMastery,setReview}:{mastery:Record<TopicId,number>;setMastery:React.Dispatch<React.SetStateAction<Record<TopicId,number>>>;setReview:React.Dispatch<React.SetStateAction<string[]>>}){const [active,setActive]=useState(0);const [answer,setAnswer]=useState("");const [answers,setAnswers]=useState<number[]>([]);const question=finalQuestions[active];function submit(){const ok=Number(answer)===question.answer;setAnswers(a=>[...a,ok?1:0]);setMastery(m=>({...m,[question.topic]:Math.max(m[question.topic],ok?80:Math.max(m[question.topic],45))}));if(!ok)setReview(r=>Array.from(new Set([...r,question.weakness])));setAnswer("");setActive(a=>a+1)} if(active>=finalQuestions.length){const score=Math.round(answers.reduce((a,b)=>a+b,0)/finalQuestions.length*100);return <div><SectionTitle kicker="Phase 1 diagnostic" title="Your current knowledge map" text="This diagnostic shows which ideas deserve another visual review."/><section className="mt-6 rounded-[2rem] bg-slate-950 p-7 text-white"><p className="text-sm text-slate-300">Mixed test result</p><p className="mt-1 text-5xl font-black">{score}%</p><p className="mt-4 max-w-lg text-slate-300">Good diagnosis is more useful than one number. Use the topic scores below to decide what to revisit.</p></section><div className="mt-6 grid gap-3 sm:grid-cols-2">{topics.map(t=><div key={t.id} className="rounded-xl bg-white p-4 shadow-sm dark:bg-slate-900"><div className="flex justify-between font-bold"><span>{t.title}</span><span>{mastery[t.id]}%</span></div><Progress value={mastery[t.id]} className="mt-3"/><p className="mt-2 text-xs text-slate-500">{mastery[t.id]<70?"Review recommended":"Strong foundation"}</p></div>)}</div></div>}return <div><SectionTitle kicker="Phase 1 final test" title={`Question ${active+1} of ${finalQuestions.length}`} text="Mixed concepts. Take your time; this is for direction, not judgement."/><section className="mt-6 rounded-[1.5rem] bg-white p-6 shadow-sm dark:bg-slate-900"><p className="text-xl font-black">{question.prompt}</p><div className="mt-5 flex gap-3"><input value={answer} onChange={e=>setAnswer(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submit()} placeholder="Your answer" inputMode="decimal" className="w-40 rounded-xl border border-slate-300 px-4 py-3 text-lg font-bold dark:bg-slate-950"/><button onClick={submit} className="rounded-xl bg-violet-600 px-5 py-3 font-bold text-white">Next question</button></div></section></div>}
function ProgressScreen({mastery,progress,review}:{mastery:Record<TopicId,number>;progress:number;review:string[]}){const label=(x:number)=>x<40?"Learning":x<70?"Developing":x<85?"Strong":"Mastered";return <div><SectionTitle kicker="Your progress" title={`${progress}% Phase 1 mastery`} text="These labels are information, never a judgement."/><div className="mt-7 grid gap-4 sm:grid-cols-2">{topics.map(t=><div key={t.id} className="rounded-2xl bg-white p-5 shadow-sm dark:bg-slate-900"><div className="flex items-center justify-between"><div><p className="font-black">{t.title}</p><p className="mt-1 text-sm text-slate-500">{label(mastery[t.id])}</p></div><span className="text-2xl font-black" style={{color:t.color}}>{mastery[t.id]}%</span></div><Progress value={mastery[t.id]} className="mt-4"/></div>)}</div>{progress>=85&&<section className="mt-7 rounded-[2rem] bg-emerald-600 p-7 text-white"><p className="text-xs font-bold uppercase tracking-widest text-emerald-100">Phase 1 — Mathematical Foundations Complete</p><h3 className="mt-2 text-3xl font-black">Next: Algebra & Functions</h3><p className="mt-3 text-emerald-50">Variables · equations · inequalities · rearranging formulas · coordinate plane · functions · y = mx + b · graphs</p></section>}<section className="mt-7 rounded-2xl border border-dashed border-slate-300 p-5 dark:border-slate-700"><p className="font-black">Review queue</p><p className="mt-2 text-sm text-slate-500">{review.length?review.join(" · "):"Nothing waiting right now. Keep practising to make this map more accurate."}</p></section></div>}
function SectionTitle({kicker,title,text}:{kicker:string;title:string;text?:string}){return <div><p className="text-xs font-bold uppercase tracking-[.16em] text-violet-600">{kicker}</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">{title}</h2>{text&&<p className="mt-3 max-w-2xl leading-7 text-slate-500">{text}</p>}</div>}
function Welcome({onClose}:{onClose:()=>void}){return <div className="fixed inset-0 z-50 grid place-items-end bg-slate-950/45 p-4 sm:place-items-center"><section role="dialog" aria-modal="true" className="w-full max-w-md rounded-[2rem] bg-white p-6 shadow-2xl dark:bg-slate-900 sm:p-8"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-100 text-violet-700"><Brain/></div><h2 className="mt-5 text-2xl font-black">How comfortable are you with mathematics?</h2><p className="mt-2 text-slate-500">This only changes the starting suggestion. You can study every topic either way.</p><div className="mt-6 space-y-2">{["Starting from basics","Know some basics","Comfortable with basic math"].map(x=><button key={x} onClick={onClose} className="w-full rounded-xl border border-slate-200 p-4 text-left font-bold hover:border-violet-400 hover:bg-violet-50 dark:border-slate-700 dark:hover:bg-violet-950/30">{x}</button>)}</div><button onClick={onClose} className="mt-5 w-full text-sm font-bold text-slate-500">Skip for now</button></section></div>}
