"use client";

import { useMemo, useState } from "react";
import { Slider } from "@/components/ui/slider";

const fmt = (n: number, digits = 2) => Number.isFinite(n) ? n.toLocaleString(undefined, { maximumFractionDigits: digits }) : "—";

export function FractionLab() {
  const [n, setN] = useState(3); const [d, setD] = useState(8);
  const filled = Math.min(n, d); const pieces = Array.from({ length: d }, (_, i) => i < filled);
  return <LabFrame eyebrow="Explore fractions" title={`${n}/${d} of one whole`} note="Move either slider. The bar and circle always show the same amount.">
    <div className="grid gap-8 lg:grid-cols-[1fr_1.1fr] lg:items-center">
      <div className="mx-auto h-44 w-44 rounded-full" style={{ background: `conic-gradient(#e85d75 0 ${(filled / d) * 100}%, #f4e9ee ${(filled / d) * 100}% 100%)` }} aria-label={`${filled} of ${d} parts shaded`} />
      <div className="space-y-5"><FractionBar numerator={filled} denominator={d} /><Control label={`Numerator: ${n}`} value={n} onChange={setN} min={0} max={12} /><Control label={`Denominator: ${d}`} value={d} onChange={setD} min={1} max={12} /><p className="text-sm text-slate-500">{n > d ? "This is an improper fraction: more than one whole." : "Each piece is equal. That equality is the important part."}</p></div>
    </div></LabFrame>
}

export function FractionBar({ numerator, denominator, tone = "rose" }: { numerator: number; denominator: number; tone?: "rose" | "violet" }) {
  return <div className="flex h-14 overflow-hidden rounded-xl border border-slate-200 bg-white" aria-label={`${numerator} divided by ${denominator}`}>
    {Array.from({ length: denominator }, (_, i) => <div key={i} className={`flex-1 border-r border-white last:border-0 ${i < numerator ? tone === "rose" ? "bg-rose-400" : "bg-violet-400" : "bg-slate-100"}`} />)}
  </div>;
}

export function PercentageLab() {
  const [p, setP] = useState(37); const [start, setStart] = useState(100); const [end, setEnd] = useState(105);
  const change = start === 0 ? 0 : ((end - start) / start) * 100;
  return <LabFrame eyebrow="Percent playground" title={`${p}% means ${p} out of 100`} note="Percent is just another way to say “out of 100.”">
    <div className="grid gap-7 lg:grid-cols-2"><div><div className="grid grid-cols-10 gap-1.5" aria-label={`${p} percent grid`}>{Array.from({ length: 100 }, (_, i) => <span key={i} className={`aspect-square rounded-[3px] ${i < p ? "bg-amber-400" : "bg-slate-100"}`} />)}</div><div className="mt-5"><Control label={`Percentage: ${p}%`} value={p} onChange={setP} min={0} max={100} /></div><p className="mt-3 text-center text-lg font-semibold text-slate-800">{p}% = {p}/100 = {(p / 100).toFixed(2)}</p></div>
      <div className="rounded-2xl bg-amber-50 p-5"><p className="text-sm font-bold text-amber-900">Percentage change lab</p><div className="mt-5 grid grid-cols-2 gap-3"><NumberInput label="Old value" value={start} setValue={setStart} /><NumberInput label="New value" value={end} setValue={setEnd} /></div><div className="mt-5 rounded-xl bg-white p-4 text-center"><p className="text-sm text-slate-500">{start} → {end} is a change of {end - start >= 0 ? "+" : ""}{fmt(end - start)}</p><p className="mt-2 text-3xl font-black text-amber-700">{change >= 0 ? "+" : ""}{fmt(change)}%</p><p className="mt-2 text-xs text-slate-500">({fmt(end - start)} ÷ {start}) × 100</p></div></div>
    </div></LabFrame>
}

export function OrderMachine() {
  const [mistake, setMistake] = useState(false); const correct = !mistake;
  return <LabFrame eyebrow="Expression machine" title="8 + 6 × 4" note="Choose a route and watch the expression transform.">
    <div className="grid gap-6 lg:grid-cols-[1fr_1.2fr]"><div className="flex rounded-xl bg-slate-100 p-1"><button onClick={() => setMistake(false)} className={`flex-1 rounded-lg px-3 py-3 text-sm font-bold ${correct ? "bg-white text-violet-700 shadow-sm" : "text-slate-500"}`}>Correct order</button><button onClick={() => setMistake(true)} className={`flex-1 rounded-lg px-3 py-3 text-sm font-bold ${!correct ? "bg-white text-rose-600 shadow-sm" : "text-slate-500"}`}>Left-to-right mistake</button></div>
      <div className={`rounded-2xl p-6 ${correct ? "bg-violet-50" : "bg-rose-50"}`}><p className="text-xs font-bold uppercase tracking-widest text-slate-500">{correct ? "Multiply first" : "This changes the meaning"}</p><div className="mt-5 space-y-3 text-center font-mono text-2xl font-bold text-slate-800"><div>8 + 6 × 4</div><div className="text-slate-400">↓</div><div>{correct ? "8 + 24" : "14 × 4"}</div><div className="text-slate-400">↓</div><div className={correct ? "text-violet-700" : "text-rose-600"}>{correct ? "32" : "56"}</div></div><p className="mt-5 text-sm text-slate-600">{correct ? "Multiplication and division happen before addition and subtraction." : "Adding first creates a different expression. It is not what 8 + 6 × 4 says."}</p></div>
    </div></LabFrame>
}

export function NumberLineLab() {
  const [start, setStart] = useState(-3); const [move, setMove] = useState(5); const result = start + move;
  const marks = Array.from({ length: 17 }, (_, i) => i - 8);
  return <LabFrame eyebrow="Number line" title={`${start} + ${move >= 0 ? "+" : ""}${move} = ${result}`} note="Adding a positive moves right. Adding a negative moves left."><div className="rounded-2xl bg-violet-50 p-5"><div className="relative mt-8 flex justify-between border-t-2 border-slate-300">{marks.map((m) => <div key={m} className="relative w-px border-l border-slate-300 pt-3 text-center text-xs text-slate-500"><span className="-translate-x-1/2 absolute">{m}</span>{m === start && <b className="absolute -top-10 -translate-x-1/2 rounded-full bg-violet-600 px-2 py-1 text-white">start</b>}{m === result && <b className="absolute -top-20 -translate-x-1/2 rounded-full bg-emerald-600 px-2 py-1 text-white">result</b>}</div>)}</div><div className="mt-12 grid gap-5 sm:grid-cols-2"><Control label={`Start: ${start}`} value={start} onChange={setStart} min={-8} max={8} /><Control label={`Add: ${move}`} value={move} onChange={setMove} min={-8} max={8} /></div></div></LabFrame>
}

export function ExponentLab() {
  const [base, setBase] = useState(2); const [power, setPower] = useState(5); const value = base ** power;
  return <LabFrame eyebrow="Growth explorer" title={`${base}^${power} = ${fmt(value, 0)}`} note="An exponent is repeated multiplication."><div className="grid gap-6 lg:grid-cols-[1.1fr_1fr]"><div className="rounded-2xl bg-orange-50 p-5"><div className="flex flex-wrap gap-2 text-lg font-black text-orange-900">{Array.from({ length: power }, (_, i) => <span key={i}>{i ? "× " : ""}{base}</span>)}</div><div className="mt-6 flex h-32 items-end gap-2">{Array.from({ length: Math.min(power, 8) }, (_, i) => <div key={i} className="flex flex-1 flex-col justify-end"><div className="rounded-t bg-orange-400" style={{ height: `${Math.min(100, ((base ** (i + 1)) / Math.max(value, 1)) * 100)}%` }} /><span className="mt-2 text-center text-xs">{base ** (i + 1)}</span></div>)}</div></div><div className="space-y-5"><Control label={`Base: ${base}`} value={base} onChange={setBase} min={2} max={5} /><Control label={`Exponent: ${power}`} value={power} onChange={setPower} min={0} max={8} /><p className="rounded-xl bg-slate-100 p-4 text-sm text-slate-600">Each new step multiplies by {base}. That is why exponential growth quickly separates from linear growth.</p></div></div></LabFrame>
}

export function RootLab() {
  const [area, setArea] = useState(81); const root = Math.sqrt(area); const perfect = Number.isInteger(root);
  return <LabFrame eyebrow="Square / root explorer" title={`√${area} ${perfect ? `= ${root}` : `≈ ${fmt(root)}`}`} note="A square root asks for the side length of a square."><div className="grid gap-6 lg:grid-cols-[1fr_1.15fr]"><div className="mx-auto flex h-48 w-48 items-center justify-center bg-emerald-400 text-3xl font-black text-emerald-950 shadow-lg" style={{ borderRadius: `${Math.max(6, 30 - root * 2)}px` }}>{fmt(area, 0)}<span className="ml-1 text-sm font-medium">area</span></div><div className="space-y-5"><Control label={`Area: ${area}`} value={area} onChange={setArea} min={1} max={144} step={1} /><div className="rounded-xl bg-emerald-50 p-4"><p className="text-sm text-emerald-900">A side of <b>{fmt(root)}</b> makes an area of <b>{fmt(root)} × {fmt(root)} = {area}</b>.</p>{!perfect && <p className="mt-2 text-sm text-slate-600">It sits between {Math.floor(root)}² = {Math.floor(root) ** 2} and {Math.ceil(root)}² = {Math.ceil(root) ** 2}.</p>}</div></div></div></LabFrame>
}

export function RatioLab() { const [a, setA] = useState(3); const [b, setB] = useState(2); const factor = Math.max(1, Math.floor(12 / Math.max(a, b))); return <LabFrame eyebrow="Ratio visualizer" title={`${a} : ${b}`} note="The relationship stays the same when both sides scale together."><div className="grid gap-6 sm:grid-cols-2"><div className="flex items-center justify-center gap-2 rounded-2xl bg-blue-50 p-5">{Array.from({ length: a }, (_, i)=><span key={i} className="h-8 w-8 rounded-full bg-blue-500"/>)}<span className="mx-2 text-xl">:</span>{Array.from({ length: b }, (_, i)=><span key={i} className="h-8 w-8 rounded-full bg-sky-300"/>)}</div><div className="space-y-5"><Control label={`First amount: ${a}`} value={a} onChange={setA} min={1} max={6}/><Control label={`Second amount: ${b}`} value={b} onChange={setB} min={1} max={6}/><p className="text-sm text-slate-600">× {factor} gives <b>{a * factor}:{b * factor}</b>. Both sides changed equally.</p></div></div></LabFrame> }

export function DecimalLab() { const [digit, setDigit] = useState(4); const [place, setPlace] = useState(1); const value = digit / 10 ** place; const labels=["ones","tenths","hundredths","thousandths"]; return <LabFrame eyebrow="Place value" title={`${digit} in the ${labels[place]} place = ${value.toFixed(place)}`} note="Each step to the right is ten times smaller."><div className="grid grid-cols-4 overflow-hidden rounded-2xl border border-teal-100">{[0,1,2,3].map((p)=><div key={p} className={`min-h-28 border-r border-teal-100 p-3 last:border-0 ${place===p?"bg-teal-50":"bg-white"}`}><p className="text-xs font-bold text-slate-500">{labels[p]}</p><p className="mt-5 text-center text-3xl font-black text-teal-700">{place===p?digit:"0"}</p></div>)}</div><div className="mt-6 grid gap-5 sm:grid-cols-2"><Control label={`Digit: ${digit}`} value={digit} onChange={setDigit} min={1} max={9}/><Control label={`Position: ${labels[place]}`} value={place} onChange={setPlace} min={0} max={3}/></div></LabFrame> }

function LabFrame({ eyebrow, title, note, children }: { eyebrow: string; title: string; note: string; children: React.ReactNode }) { return <section className="rounded-[1.7rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><p className="text-xs font-bold uppercase tracking-[0.16em] text-violet-600">{eyebrow}</p><h3 className="mt-2 text-2xl font-black tracking-tight text-slate-900 sm:text-3xl">{title}</h3><p className="mt-2 max-w-2xl text-slate-600">{note}</p><div className="mt-7">{children}</div></section> }
function Control({ label, value, onChange, min, max, step=1 }: { label:string; value:number; onChange:(v:number)=>void; min:number; max:number; step?:number }) { return <div><div className="mb-3 flex justify-between text-sm font-bold text-slate-700"><label>{label}</label><span className="text-slate-400">{min}–{max}</span></div><Slider value={[value]} onValueChange={([v])=>onChange(v)} min={min} max={max} step={step} className="[&_[data-slot=slider-range]]:bg-violet-600" /></div> }
function NumberInput({label,value,setValue}:{label:string;value:number;setValue:(v:number)=>void}) { return <label className="text-sm font-medium text-slate-600">{label}<input aria-label={label} type="number" value={value} onChange={e=>setValue(Number(e.target.value))} className="mt-1.5 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-lg font-bold text-slate-900" /></label> }

export function MarketReturnLab() { const [entry,setEntry]=useState(100); const [exit,setExit]=useState(105); const [size,setSize]=useState(10); const abs=exit-entry; const ret=entry?abs/entry*100:0; return <section className="rounded-[1.7rem] bg-slate-950 p-6 text-white sm:p-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-amber-300">Market return lab</p><h3 className="mt-2 text-2xl font-black">From price move to return</h3><div className="mt-6 grid gap-3 sm:grid-cols-3"><DarkInput label="Entry price" value={entry} setValue={setEntry}/><DarkInput label="Exit price" value={exit} setValue={setExit}/><DarkInput label="Units" value={size} setValue={setSize}/></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><Metric label="Price change" value={`${abs>=0?"+":""}${fmt(abs)}`}/><Metric label="Return" value={`${ret>=0?"+":""}${fmt(ret)}%`}/><Metric label="P/L" value={`${abs*size>=0?"+":""}$${fmt(abs*size)}`}/></div><p className="mt-6 text-sm text-slate-300">First we find the change: {exit} − {entry} = {fmt(abs)}. Then we compare it with the entry: {fmt(abs)} ÷ {entry} = {fmt(ret/100,4)} = {fmt(ret)}%.</p></section> }
function DarkInput({label,value,setValue}:{label:string;value:number;setValue:(v:number)=>void}) { return <label className="text-sm text-slate-300">{label}<input aria-label={label} type="number" value={value} onChange={e=>setValue(Number(e.target.value))} className="mt-1.5 w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-lg font-bold text-white" /></label>};
function Metric({label,value}:{label:string;value:string}) { return <div className="rounded-xl bg-white/10 p-4"><p className="text-xs text-slate-400">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div> }
