export type TopicId = "order" | "fractions" | "decimals" | "percentages" | "ratios" | "negatives" | "exponents" | "roots";

export type Topic = {
  id: TopicId;
  number: number;
  title: string;
  short: string;
  intuition: string;
  why: string;
  example: string;
  quant: string;
  color: string;
  practice: { prompt: string; answer: number; hint: string; explanation: string; weakness: string };
};

export const topics: Topic[] = [
  { id: "order", number: 1, title: "Order of Operations", short: "Make expressions mean one thing.", intuition: "An expression is like a recipe. If we do its steps in a different order, we can get a different answer.", why: "Brackets say “do this group first.” Powers come next. Multiplication and division share one level: work left to right. Addition and subtraction also share one level.", example: "8 + 6 × 4 = 8 + 24 = 32", quant: "A trading formula can contain prices, fees and position size. One wrong order can turn a correct calculation into a bad trade decision.", color: "#8373f5", practice: { prompt: "What is 12 − 3 × 2?", answer: 6, hint: "Multiply before subtracting.", explanation: "3 × 2 is 6, so 12 − 6 = 6.", weakness: "order-of-operations.precedence" } },
  { id: "fractions", number: 2, title: "Fractions", short: "See parts of one equal whole.", intuition: "A fraction tells us how much of one whole we have. The bottom number tells how many equal pieces. The top number tells how many pieces we have.", why: "We need common denominators to add because every piece must be the same size before we count them together.", example: "1/2 + 1/4 = 2/4 + 1/4 = 3/4", quant: "Fractions appear in position sizing, partial exits and probabilities. Seeing their size helps you spot impossible calculations.", color: "#e85d75", practice: { prompt: "What is 1/2 + 1/4? Write the answer as a decimal.", answer: 0.75, hint: "Turn one-half into fourths first.", explanation: "1/2 is 2/4. Then 2/4 + 1/4 = 3/4 = 0.75.", weakness: "fractions.common-denominator" } },
  { id: "decimals", number: 3, title: "Decimals", short: "Place value makes a number precise.", intuition: "Digits after the dot are smaller pieces of one. 0.4 means four tenths; 0.04 means four hundredths.", why: "Moving one place left makes a digit ten times larger. Moving right makes it ten times smaller.", example: "23.475 = 2 tens + 3 ones + 4 tenths + 7 hundredths + 5 thousandths", quant: "Prices, spreads and returns are often decimals. A tiny decimal difference can still be meaningful when position size is large.", color: "#269b93", practice: { prompt: "Which is larger: 0.8 or 0.75? Enter the larger number.", answer: 0.8, hint: "0.8 is the same as 0.80.", explanation: "80 hundredths is more than 75 hundredths.", weakness: "decimals.place-value" } },
  { id: "percentages", number: 4, title: "Percentages", short: "Compare every change to 100.", intuition: "Percent means “out of 100.” So 37% means 37 pieces out of 100, or 0.37 of one whole.", why: "A percentage change is compared with the starting value because the starting value is the reference point.", example: "100 → 105 is +5. Compared with 100, that is 5/100 = 5%.", quant: "Returns, drawdowns, fees and win rate are all percentages. A +10% gain then a −10% loss ends at 99, not 100.", color: "#f29b38", practice: { prompt: "A price goes from 200 to 230. What is the percentage increase?", answer: 15, hint: "Find the change, then compare it with 200.", explanation: "The change is 30. 30 ÷ 200 = 0.15 = 15%.", weakness: "percentages.percentage-change" } },
  { id: "ratios", number: 5, title: "Ratios & Proportions", short: "Compare two quantities clearly.", intuition: "A ratio tells how two amounts relate. 3:2 means that for every 3 of the first thing, there are 2 of the second.", why: "Equivalent ratios keep the same relationship by scaling both sides by the same amount.", example: "3:2 = 6:4 = 9:6", quant: "Risk/reward is a ratio. It is different from win rate: 30 wins and 20 losses is a 3:2 ratio, while win rate is 30/50 = 60%.", color: "#4b7bec", practice: { prompt: "If 3/5 = 12/x, what is x?", answer: 20, hint: "3 became 12 by multiplying by 4.", explanation: "Scale the other side by 4 too: 5 × 4 = 20.", weakness: "ratios.proportions" } },
  { id: "negatives", number: 6, title: "Negative Numbers", short: "Use direction, not fear.", intuition: "Negative numbers are positions below zero. On a number line, right is larger and left is smaller.", why: "Adding a positive moves right. Subtracting moves left. For multiplication, the pattern stays consistent as one factor passes through zero.", example: "−3 + 5 = 2", quant: "Profit and loss uses signed numbers. A sequence of +2R, −1R, +0.5R becomes your running equity curve.", color: "#c66bda", practice: { prompt: "What is 3 − 7?", answer: -4, hint: "Start at 3 and move 7 steps left.", explanation: "Moving left from 3 by 7 lands at −4.", weakness: "negatives.subtraction" } },
  { id: "exponents", number: 7, title: "Powers & Exponents", short: "Repeated multiplication, compactly written.", intuition: "2³ means multiply three 2s: 2 × 2 × 2. The small number tells how many copies of the base to multiply.", why: "When multiplying the same base, you join all the copies, so exponents add: x² × x³ = x⁵.", example: "2⁵ = 2 × 2 × 2 × 2 × 2 = 32", quant: "Compounding is exponential. Capital growing 10% for three periods is 100 × 1.1³ = 133.1.", color: "#e67b4e", practice: { prompt: "What is 2³?", answer: 8, hint: "Multiply three 2s.", explanation: "2 × 2 × 2 = 8.", weakness: "exponents.repeated-multiplication" } },
  { id: "roots", number: 8, title: "Roots", short: "Find the side from the square.", intuition: "A square root reverses squaring. √81 asks: what side length makes a square with area 81? The answer is 9.", why: "Squaring and square roots undo each other. √50 is a little more than 7 because 7² = 49.", example: "9² = 81, therefore √81 = 9", quant: "Later, standard deviation uses a square root. For now, know that a root turns a squared quantity back to its original scale.", color: "#5caf81", practice: { prompt: "What is √81?", answer: 9, hint: "Which number times itself makes 81?", explanation: "9 × 9 = 81, so √81 = 9.", weakness: "roots.square-root" } },
];

export const topicById = Object.fromEntries(topics.map((topic) => [topic.id, topic])) as Record<TopicId, Topic>;
